/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIdRouteImport } from './routes/productos.$id'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIdRoute = ProductosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/productos': typeof ProductosRouteWithChildren
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/productos': typeof ProductosRouteWithChildren
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/productos': typeof ProductosRouteWithChildren
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/productos'
    | '/productos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/productos'
    | '/productos/$id'
  id:
    | '__root__'
    | '/'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/productos'
    | '/productos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRoute
  CuentaRoute: typeof CuentaRoute
  ProductosRoute: typeof ProductosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$id': {
      id: '/productos/$id'
      path: '/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof ProductosIdRouteImport
      parentRoute: typeof ProductosRoute
    }
  }
}

interface ProductosRouteChildren {
  ProductosIdRoute: typeof ProductosIdRoute
}

const ProductosRouteChildren: ProductosRouteChildren = {
  ProductosIdRoute: ProductosIdRoute,
}

const ProductosRouteWithChildren = ProductosRoute._addFileChildren(
  ProductosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRoute,
  CuentaRoute: CuentaRoute,
  ProductosRoute: ProductosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
